name: ci-quack-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    name: Check application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # Configura o reposit√≥rio no ambiente
      - uses: actions/setup-node@v4 # Configura o NodeJS
        with:
          node-version: '20.19.0'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn test
