# name: ci-quack-workflow
# on: [pull_request]
# jobs:
#   check-application:
#     name: Check application
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2 # Configura o repositório no ambiente
#       - uses: actions/setup-node@v2 # Configura o NodeJS
#         with:
#           node-version: '20.19.0'
#       - run: yarn install
#       - run: yarn test



name: ci-quack-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    name: Check application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Configura o repositório no ambiente
      - uses: actions/setup-node@v2 # Configura o NodeJS
        with:
          node-version: '20.19.0'
      - run: yarn install
      - run: yarn test
