name: ci-quack-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    name: Check application
    runs-on: ubuntu-latest
    # strategy:
      # matrix:
        # node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v5 # Configura o reposit√≥rio no ambiente
      - uses: actions/setup-node@v4 # Configura o NodeJS
        with:
          # node-version: ${{ matrix.node-version }}
          node-version: 20.x
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn test
